services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
      - ./backend/public/storage:/var/www/html/public/storage
    environment:
      - APP_URL=http://laravel:8000
      - APP_ENV=local
      - APP_KEY=base64:z1kLPlST3D4cWwmLbCwy5hSQ7QxNOFbynUb0WxJA7HE=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=meinprojekt
      - DB_USERNAME=root
      - DB_PASSWORD=test12345678
    depends_on:
      - db
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "db:3306", "--", "php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test12345678
      MYSQL_DATABASE: meinprojekt
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./backend/meinprojekt.sql:/docker-entrypoint-initdb.d/meinprojekt.sql:ro

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge
