version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Das Verzeichnis, in dem sich Ihre Dockerfile befindet
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_URL=http://laravel:8000
      - APP_ENV=local
      - APP_KEY=base64:z1kLPlST3D4cWwmLbCwy5hSQ7QxNOFbynUb0WxJA7HE=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=meinprojekt
      - DB_USERNAME=root
      - DB_PASSWORD=test12345678
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test12345678
      MYSQL_DATABASE: meinprojekt
    ports:
      - "3306:3306"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true



networks:
  app-network:
    driver: bridge
